Repository obophenotype/uberon, pull requests merged in 2024-08, with the labels that each got.

#3345 Fix #3344 broken link to SSOM documentation
  docs/bridges.md
Labels: documentation issue

#3343 NTR humeral circumflex arteries
  src/patterns/data/default/artery_and_arteriole_pattern.tsv
  src/patterns/definitions.owl
  src/patterns/pattern.owl
Labels: new term request, HuBMAP, vasculature

#3348 Add ethmoidal veins
  src/patterns/data/default/vein_and_venule_pattern.tsv
  src/patterns/definitions.owl
Labels: new term request, HuBMAP
